SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS `TOTAL_SALES`
FROM (
    SELECT PRODUCT_ID, PRODUCT_NAME, PRICE
    FROM FOOD_PRODUCT FP
) FP
INNER JOIN (
    SELECT PRODUCT_ID, AMOUNT
    FROM FOOD_ORDER FO
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
) FO
USING (PRODUCT_ID)
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY `TOTAL_SALES` DESC, PRODUCT_ID
;
