SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM (
    SELECT USER_ID, GENDER
    FROM USER_INFO UI
    WHERE GENDER IS NOT NULL
) UI
INNER JOIN (
    SELECT USER_ID, 
        YEAR(SALES_DATE) AS `YEAR`, 
        MONTH(SALES_DATE) AS `MONTH`
    FROM ONLINE_SALE
) OS
USING (USER_ID)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
;
