SELECT FLAVOR
FROM (
    SELECT *
    FROM (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF FH
        WHERE TOTAL_ORDER > 3000
    ) FH
    INNER JOIN (
        SELECT FLAVOR
        FROM ICECREAM_INFO II
        WHERE INGREDIENT_TYPE = 'fruit_based'
    ) II
    USING (FLAVOR)
    ORDER BY TOTAL_ORDER DESC
) T
;
