SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS `TOTAL_SALES`
FROM (
    SELECT BOOK_ID, AUTHOR_ID, CATEGORY, PRICE
    FROM BOOK B
) B
INNER JOIN AUTHOR A
USING (AUTHOR_ID)
INNER JOIN (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES BS
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
) BS
USING (BOOK_ID)
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
;
