SELECT *
FROM (
    SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * 30 * (1 - (DISCOUNT_RATE * 0.01))) AS `FEE`
    FROM (
        SELECT CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR CRCC
        WHERE CAR_TYPE IN ('세단', 'SUV')
    ) CRCC
    INNER JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
        WHERE DURATION_TYPE = '30일 이상'
    ) CRCDP
    USING (CAR_TYPE)
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
        WHERE (START_DATE <= '2022-11-30' AND '2022-11-01' <= END_DATE)
    )
) T
WHERE (500000 <= `FEE` AND `FEE` < 2000000)
ORDER BY `FEE` DESC, CAR_TYPE, CAR_ID DESC
;
