SELECT *
FROM (
    SELECT USER_ID, NICKNAME,
        CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS `전체주소`,
        CONCAT_WS('-', LEFT(TLNO, 3), MID(TLNO, 4, 4), RIGHT(TLNO, 4)) AS `전화번호`
    FROM USED_GOODS_USER UGU
) UGU
INNER JOIN (
    SELECT WRITER_ID AS `USER_ID`
    FROM USED_GOODS_BOARD UGB
    GROUP BY USER_ID
    HAVING COUNT(BOARD_ID) >= 3
) UGB
USING (USER_ID)
ORDER BY USER_ID DESC
;
