SELECT *
FROM (
    SELECT USER_ID, NICKNAME
    FROM USED_GOODS_USER UGU
) UGU
INNER JOIN (
    SELECT WRITER_ID AS `USER_ID`, SUM(PRICE) AS `TOTAL_SALES`
    FROM USED_GOODS_BOARD UGB
    WHERE `STATUS` = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) UGB
USING (USER_ID)
ORDER BY TOTAL_SALES
;
