SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS AI
INNER JOIN ANIMAL_OUTS AO
USING (ANIMAL_ID, ANIMAL_TYPE, NAME)
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact %'
AND (AO.SEX_UPON_OUTCOME LIKE 'Spayed %'
    OR AO.SEX_UPON_OUTCOME LIKE 'Neutered %')
ORDER BY ANIMAL_ID
;
